version: '3.4'

services:

  haproxy:
    image: haproxy:latest
    volumes:
      - "./haproxy/conf:/usr/local/etc/haproxy:ro"
      - "./ssl:/etc/ssl/mine:ro"
      # Redirecting HAProxy logs can be troublesome
      # The container /dev/log to host /dev/log does
      # the trick, though.
      - "/dev/log:/dev/log"
    restart: always
    ports:
      - 80:80
      - 443:443
    networks:
      haproxy_net:
        aliases:
          - haproxy

  nginx:
    image: nginx:alpine
    volumes:
      - "./www:/usr/share/nginx/website:ro"
      - "./nginx/config/nginx.conf:/etc/nginx/nginx.conf:ro"
      - "./nginx/cache:/var/cache/nginx"
      - "./nginx/run:/var/run"
      - "./nginx/logs:/var/log/nginx"
    restart: always
    networks:
      haproxy_net:
        aliases:
          - that_nginx_server

networks:
  haproxy_net:
